column_limit: 70
indent_width: 1
use_tab: true
tab_width: 2
continuation_indent_width: 1
align_args: false
break_after_functioncall_lp: true
break_before_functioncall_rp: true
align_parameter: false
chop_down_parameter: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
align_table_field: false
break_after_table_lb: true
break_before_table_rb: true
chop_down_table: true
chop_down_kv_table: true
single_quote_to_double_quote: true
