#!/bin/sh
sxhkd &
numlockx on &
dunst &
compton -b --config ~/.config/compton/compton.conf &
xrdb -load ~/.Xdefaults &
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp $HOME/.fonts
xset fp rehash
xrandr --output DVI-I-2 --primary
xrandr --output DVI-I-3 --auto --left-of DVI-I-2

export BSPWM_TREE=/tmp/bspwm.tree
export BSPWM_HISTORY=/tmp/bspwm.history
export BSPWM_STACK=/tmp/bspwm.stack

export PANEL_FIFO="/tmp/panel-fifo"
export PATH=$PATH:~/.config/bspwm/panel/


#Loop
if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

## Monitor Setup
wmname LG3D &
bspc monitor -f ^1
bspc monitor ^1 --reset-desktops 'URXVT' 'VIM' 'SSH' 'IRC' 'SUBL'
bspc monitor ^2 --reset-desktops 'CHROME' 'PDF' 'FIREFOX' 'THUNAR' 'MEDIA'


## SETTINGS {{{
bspc config border_width                    1
bspc config window_gap                      5
bspc config top_padding                     20
bspc config left_padding                    2
bspc config right_padding                   2
bspc config bottom_padding                  2
bspc config focused_frame_opacity           0.5
bspc config normal_frame_opacity            0.2

bspc config growth_factor                   0.1
bspc config split_ratio                     0.50
bspc config borderless_monocle              false
bspc config gapless_monocle                 false
bspc config focus_follows_pointer           true
bspc config history_aware_focus             true
bspc config auto_alternate                  true
bspc config auto_cancel                     true
bspc config apply_floating_atom             true
bspc config ignore_ewmh_focus               true
## }}}


## COLORS {{{
bspc config focused_border_color            "#03a9f4"
bspc config normal_border_color             "#81d4fa"

bspc config focused_sticky_border_color     "#8bc34a"
bspc config normal_sticky_border_color      "#ceecab"

bspc config focused_locked_border_color     "#ffc107"
bspc config normal_locked_border_color      "#ffa000"

bspc config focused_private_border_color    "#cfd8dc"
bspc config normal_private_border_color     "#eceff1"

bspc config urgent_border_color             "#ff9800"
bspc config presel_border_color             "#ffa74d"
## }}}

# Rules
bspc rule -a Firefox desktop=^8
bspc rule -a Subl3 desktop=^5
bspc rule -a Thunar  desktop=^9
bspc rule -a google-chrome desktop=^6
bspc rule -a "crx_nckgahadagoaajjgafhacjanaoiihapd" floating=true
#Background
exec sh ~/.fehbg & ~/.config/bspwm/panel/panel &> /tmp/panel.log
