#!/bin/sh
setxkbmap -layout latam
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp $HOME/.fonts
xset fp rehash

bspc monitor -d I II III IV V VI VII VIII IX X

export PANEL_FIFO="/tmp/panel-fifo"
export PATH=$PATH:~/.config/bspwm/panel/

# Visual options
bspc config split_ratio         0.50
bspc config border_width        1
bspc config window_gap          4
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true


## SETTINGS {{{
bspc config border_width                    1
bspc config window_gap                      10
bspc config top_padding                     14
bspc config left_padding                    -6
bspc config right_padding                   -6
bspc config bottom_padding                  -6
bspc config focused_frame_opacity           0.05
bspc config normal_frame_opacity            0.0

bspc config growth_factor                   0.03
bspc config split_ratio                     0.50
bspc config borderless_monocle              false
bspc config gapless_monocle                 false
bspc config focus_follows_pointer           true
bspc config history_aware_focus             true
bspc config auto_alternate                  true
bspc config auto_cancel                     true
bspc config apply_floating_atom             true
bspc config ignore_ewmh_focus               true
## }}}


## COLORS {{{
bspc config focused_border_color            "#bb9584"
bspc config normal_border_color             "#645240"
bspc config focused_sticky_border_color     "#beb55b"
bspc config normal_sticky_border_color      "#646240"
bspc config focused_locked_border_color     "#cb6077"
bspc config normal_locked_border_color      "#646240"
bspc config focused_private_border_color    "#a89bb9"
bspc config normal_private_border_color     "#646240"
bspc config urgent_border_color             "#e9e1dd"
bspc config presel_border_color             "#fdf6e3"
## }}}


bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
#bspc rule -a "Thunar" pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off


exec sh ~/.fehbg & ~/.config/bspwm/panel/panel &> /tmp/panel.log
