pulse.rules = [
  {
    matches = [
      {
        pipewire.access.portal.app_id = "com.discordapp.Discord"
      }
    ]
    actions = {
      quirks = [
        block-source-volume
        block-sink-volume
      ]
    }
  }
]
